defaults: &defaults
  user_email: "s2-order-management-app" 
  study_uuid: "55555555-2222-3333-6666-777777777777"
  cost_code: "cost code"

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
